GET http://localhost:3040/
###

POST http://localhost:3040/register/
Content-Type: application/json

{
        "fullname":"Anurag",
        "email":"anuraggoudga@gmail.com",
        "mobile":"745387548",
        "skills":"node.js",
        "password":"anurag2245",
        "confirmPassword":"anurag2245"
}
###
POST http://localhost:3040/login
Content-Type: application/json
{
     "email":"anuraggoudanu@gmail.com",
        "password":"anurag7093"

}
###
GET http://localhost:3043/alldevelopers