GET http://localhost:3045/
###

POST http://localhost:3045/register/
Content-Type: application/json

{
        "fullname":"Anurag",
        "email":"anurag123@gmail.com",
        "mobile":"745387548",
        "skills":"node.js",
        "password":"anurag22",
        "confirmPassword":"anurag22"
}
###
POST http://localhost:3045/login
Content-Type: application/json

{
     "email":"anurag123@gmail.com",
        "password":"anurag22"

}
###
GET http://localhost:3045/alldevelopers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiZTFkMmZjMGEwY2E2N2Y3NjExMzU4IiwiaWF0IjoxNjkwMTgwOTc1LCJleHAiOjYyOTAxODA5NzV9.ChXUGk4Emzi5SiWnSnaSpfe-RsfpRmjZIql8e9nzomg   

###
GET http://localhost:3045/individualProfile/64be0400377f5d6c04f849ce
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjRiZTFkMmZjMGEwY2E2N2Y3NjExMzU4IiwiaWF0IjoxNjkwMTgwOTc1LCJleHAiOjYyOTAxODA5NzV9.ChXUGk4Emzi5SiWnSnaSpfe-RsfpRmjZIql8e9nzomg   
